### ISSUE TITLE
As a doctor, I can add a new visitation with details in a popup window 

### ISSUE THREAD

**Issue by afroneth** [AY2021S1-CS2103T-W11-4/tp#87]

**Comment by eugene3231** [comment]
**Todo:**

- [ ] 1. Fix test files - patient constructors
- [x] 2. Fix Visit object save format in clinical.json
- [x] 3. Improve overall code style and checkstyle
- [x] 4. Improve overall UI of popup window
- [x] 5. Fix null pointer - message
- [x] 6. Update list of patients in patient tab when add visit
- [ ] 7. Resizing of profile window - responsive (v1.4)
- [x] 8. EditVisit (ken)
- [x] 9. DeleteVisit (eug)
- [scraped] 10. Show only 3 most recent visits under each patient
- [ ] 10. Total counts of visit per patient to be displayed in profile panel with index of each visit
- [x] 11. Standardize the /ev /i etc prefixes for new features e.g. addvisit, editvisit and deletevisit
- [x] 12. Ensure icons are using stethoscope for new popup windows

Appointment:
- [ ] 1. Add in notice that user have to change the appointment details also, after editing finish a patient (problem due to 'snapshotting' of patient details when creating appointment)

**Comment by eugene3231** [comment]
Removed the ev/ and d/ for editvisit and deletevisit, the visit index will be i/
changed i/ to ic/ for addpatient, editpatient

change addPicture command to addpicture

ctrl + s to save

shortcut to switch tab in main screen: ctrl + tab

EDIT: all done
